---
title: "01 - Dataset download and preprocessing"
author: "Elena Sasso, Luca Lepore, Marco Cominelli"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Download all the original datasets

```{r}
filename <- "https://cbioportal-datahub.s3.amazonaws.com/brca_metabric.tar.gz"

# Check that the final size of "temporary.tar.gz" is exactly 486.7 MB (otherwise 
# remove it and re-download)
options(timeout=200)
download.file(filename, destfile = "temporary.tar.gz") # In case of errors due to timeout, try to increase the timeout in the above command

# Check that all 3 files are there (might not be the case): 
# - data_clinical_sample.txt
# - data_clinical_patient.txt
# - data_mrna_illumina_microarray_zscores_ref_diploid_samples.txt
untar("temporary.tar.gz",list=TRUE)

# Download only those 3 files (the previous command just displays their names)
untar("temporary.tar.gz",files=c("brca_metabric/data_clinical_sample.txt",
                                 "brca_metabric/data_clinical_patient.txt",
                                 "brca_metabric/data_mrna_illumina_microarray_zscores_ref_diploid_samples.txt")
     )

# Remove the useless .tar.gz
file.remove(filename = 'temporary.tar.gz')

# Download the original METABRIC_RNA_Mutation.csv dataset.
# If it fails, ask Luca to make the repository public!!
filename <- "https://raw.githubusercontent.com/lulepo99/breast-cancer-survival-analysis/main/METABRIC_RNA_Mutation.csv"
download.file(filename, destfile = "METABRIC_RNA_Mutation.csv")
```

Save them inside a dataframe, one for each

```{r}
# Save it in a dataframe
METABRIC_RNA_Mutation <- read.table(file = 'METABRIC_RNA_Mutation.csv',
                                    header = TRUE,
                                    sep = ",")

# First dataframe
df_with_tmb <- read.table(file = 'brca_metabric/data_clinical_sample.txt', sep="\t",
                          header = TRUE)
# Second dataframe
df_with_relapse <- read.table(file = 'brca_metabric/data_clinical_patient.txt', sep="\t",
                              header = TRUE)

# Third dataframe
df_with_genes <- read.table(file = 'brca_metabric/data_mrna_illumina_microarray_zscores_ref_diploid_samples.txt',
                            sep="\t",
                            header = TRUE)
expr_transposed <- t(df_with_genes)
```

Pre-processing: merge them to have all the variables needed inside one unique dataset

```{r}
df_with_tmb <- df_with_tmb[-c(1986:2509),] # We take only the first 1985 rows
df_with_tmb$patient_id <- as.integer(substr(df_with_tmb$PATIENT_ID, 4, 7)) # We convert the patient_id in the format used by METABRIC_RNA_Mutation

total <- merge(METABRIC_RNA_Mutation, df_with_tmb, by ="patient_id") # First merge (to gain the TMB variable)
total <- total[,-c(694:705)]

df_with_relapse <- df_with_relapse[-c(1986:2509),] # We take only the first 1985 rows
df_with_relapse$patient_id <- as.integer(substr(df_with_relapse$PATIENT_ID, 4, 7))

total2 <- merge(total, df_with_relapse, by ="patient_id") # Second merge (to gain the RFS_STATUS and RFS_months variables)
total2 <- total2[,-c(695:716)]

METABRIC_NEW <- total2[,c(1:31,694:696,32:693)] # The METABRIC dataset with the above new variables

rm(total,total2,df_with_relapse,df_with_tmb) # Remove the intermediate dataframes

METABRIC_NEW <- METABRIC_NEW[,-c(35:523)] # We remove the columns about genes informations because we'll take those informations from a third dataset
colnames(expr_transposed) <- expr_transposed[1,]
expr_transposed <- expr_transposed[-c(1,2),]
expr_transposed <- as.data.frame(expr_transposed)
expr_transposed$patient_id <- as.integer(substr(rownames(expr_transposed), 4, 7))

total3 <- merge(METABRIC_NEW, expr_transposed, by ="patient_id") # Third merge (to gain all gene expression variables)
total3 <- total3[,c(1:34, 208:20810,35:207)]

METABRIC_NEW_GENES <- total3 # The METABRIC dataset with the above new variables + all gene expression variables

rm(expr_transposed, total3) # Remove the intermediate dataframes

```

Conversion of RFS_STATUS column

```{r}
METABRIC_NEW$RFS_STATUS <- as.integer(substr(METABRIC_NEW$RFS_STATUS, 1, 1))
METABRIC_NEW_GENES$RFS_STATUS <- as.integer(substr(METABRIC_NEW_GENES$RFS_STATUS, 1, 1))
```

Optional: to save disk space, remove the files

```{r}
# Remove the only large file
file.remove(filename = 'brca_metabric/data_mrna_illumina_microarray_zscores_ref_diploid_samples.txt')

# Optional (the following files are very small):
# file.remove(filename = 'brca_metabric/data_clinical_patient.txt')
# file.remove(filename = 'brca_metabric/data_clinical_sample.txt')
```
